package de.zwegen.zpaint.tools

import androidx.annotation.DrawableRes
import androidx.annotation.IdRes
import androidx.annotation.StringRes
import de.zwegen.zpaint.R
import de.zwegen.zpaint.colorpicker.R as ColorPickerR
import de.zwegen.zpaint.common.INVALID_RESOURCE_ID
import de.zwegen.zpaint.tools.Tool.StateChange
import java.util.EnumSet

/**
 * Zaint's complete visible editor catalog: drawing tools, document actions,
 * layer actions, filters, and editor panels.
 */
enum class ZaintToolKind(
    @get:StringRes val nameResource: Int,
    @get:StringRes val helpTextResource: Int,
    @get:DrawableRes val drawableResource: Int,
    private val stateChangeBehaviour: EnumSet<StateChange>,
    @get:IdRes val toolButtonID: Int,
    @get:DrawableRes val overlayDrawableResource: Int,
    private val hasOptions: Boolean
) {
    PIPETTE(
        R.string.button_pipette,
        R.string.help_content_eyedropper,
        R.drawable.ic_zpaint_tool_pipette,
        EnumSet.of(StateChange.ALL),
        R.id.zpaint_tools_pipette,
        INVALID_RESOURCE_ID,
        false
    ),
    BRUSH(
        R.string.button_brush,
        R.string.help_content_brush,
        R.drawable.ic_zpaint_tool_brush,
        EnumSet.of(StateChange.ALL),
        R.id.zpaint_tools_brush,
        INVALID_RESOURCE_ID,
        true
    ),
    UNDO(
        R.string.button_undo,
        R.string.help_content_undo,
        R.drawable.ic_zpaint_undo,
        EnumSet.of(StateChange.ALL),
        R.id.zpaint_btn_top_undo,
        INVALID_RESOURCE_ID,
        false
    ),
    REDO(
        R.string.button_redo,
        R.string.help_content_redo,
        R.drawable.ic_zpaint_redo,
        EnumSet.of(StateChange.ALL),
        R.id.zpaint_btn_top_redo,
        INVALID_RESOURCE_ID,
        false
    ),
    FILL(
        R.string.button_fill,
        R.string.help_content_fill,
        R.drawable.ic_zpaint_tool_fill,
        EnumSet.of(StateChange.ALL),
        R.id.zpaint_tools_fill,
        INVALID_RESOURCE_ID,
        true
    ),
    CLIPBOARD(
        R.string.button_clipboard,
        R.string.help_content_clipboard,
        R.drawable.ic_zpaint_tool_clipboard,
        EnumSet.of(StateChange.ALL),
        INVALID_RESOURCE_ID,
        INVALID_RESOURCE_ID,
        true
    ),
    SELECTION(
        R.string.button_selection,
        R.string.help_content_selection,
        R.drawable.ic_zpaint_tool_selection,
        EnumSet.of(StateChange.ALL),
        R.id.zpaint_tools_selection,
        INVALID_RESOURCE_ID,
        true
    ),
    LINE(
        R.string.button_line,
        R.string.help_content_line,
        R.drawable.ic_zpaint_tool_line,
        EnumSet.of(StateChange.ALL),
        INVALID_RESOURCE_ID,
        INVALID_RESOURCE_ID,
        true
    ),
    IMPORTPNG(
        R.string.button_import_image,
        R.string.help_content_import_png,
        R.drawable.ic_zpaint_tool_import,
        EnumSet.of(StateChange.ALL),
        R.id.zpaint_tools_import,
        INVALID_RESOURCE_ID,
        false
    ),
    TRANSFORM(
        R.string.button_transform,
        R.string.help_content_transform,
        R.drawable.ic_zpaint_tool_resize_adjust,
        EnumSet.of(StateChange.RESET_INTERNAL_STATE, StateChange.NEW_IMAGE_LOADED),
        R.id.zpaint_tools_transform,
        INVALID_RESOURCE_ID,
        true
    ),
    BORDER(
        R.string.button_border,
        R.string.help_content_border,
        R.drawable.ic_zpaint_tool_border,
        EnumSet.of(StateChange.RESET_INTERNAL_STATE, StateChange.NEW_IMAGE_LOADED),
        R.id.zpaint_tools_border,
        INVALID_RESOURCE_ID,
        true
    ),
    PERSPECTIVE(
        R.string.button_perspective,
        R.string.help_content_perspective,
        R.drawable.ic_zpaint_tool_perspective,
        EnumSet.of(StateChange.NEW_IMAGE_LOADED),
        R.id.zpaint_tools_perspective,
        INVALID_RESOURCE_ID,
        false
    ),
    PLACE(
        R.string.button_place,
        R.string.help_content_place,
        R.drawable.ic_zpaint_tool_place,
        EnumSet.of(StateChange.RESET_INTERNAL_STATE, StateChange.NEW_IMAGE_LOADED),
        R.id.zpaint_tools_place,
        INVALID_RESOURCE_ID,
        false
    ),
    ROTATE(
        R.string.button_rotate,
        R.string.help_content_rotate,
        R.drawable.ic_zpaint_tool_rotate,
        EnumSet.of(StateChange.NEW_IMAGE_LOADED),
        R.id.zpaint_tools_rotate,
        INVALID_RESOURCE_ID,
        true
    ),
    ALIGN(
        R.string.button_align,
        R.string.help_content_align,
        R.drawable.ic_zpaint_tool_align,
        EnumSet.of(StateChange.NEW_IMAGE_LOADED),
        R.id.zpaint_tools_align,
        INVALID_RESOURCE_ID,
        false
    ),
    SPEECH_BUBBLE(
        R.string.help_title_speech_bubble,
        R.string.help_content_speech_bubble,
        R.drawable.ic_zpaint_tool_speech_bubble,
        EnumSet.of(StateChange.ALL),
        R.id.zpaint_tools_speech_bubble,
        INVALID_RESOURCE_ID,
        true
    ),
    SHADOW(
        R.string.button_shadow,
        R.string.help_content_shadow,
        R.drawable.ic_zpaint_tool_shadow,
        EnumSet.of(StateChange.ALL),
        R.id.zpaint_tools_shadow,
        INVALID_RESOURCE_ID,
        true
    ),
    ERASER(
        R.string.button_eraser,
        R.string.help_content_eraser,
        R.drawable.ic_zpaint_tool_eraser,
        EnumSet.of(StateChange.ALL),
        R.id.zpaint_tools_eraser,
        INVALID_RESOURCE_ID,
        true
    ),
    ICON(
        R.string.button_shape,
        R.string.help_content_shape,
        R.drawable.ic_zpaint_tool_icons,
        EnumSet.of(StateChange.ALL),
        R.id.zpaint_tools_rectangle,
        INVALID_RESOURCE_ID,
        true
    ),
    TEXT(
        R.string.button_text,
        R.string.help_content_text,
        R.drawable.ic_zpaint_tool_text,
        EnumSet.of(StateChange.ALL),
        R.id.zpaint_tools_text,
        INVALID_RESOURCE_ID,
        true
    ),
    LAYER(
        R.string.layers_title,
        R.string.help_content_layer,
        R.drawable.ic_zaint_bottom_navigation_layers,
        EnumSet.of(StateChange.ALL),
        INVALID_RESOURCE_ID,
        INVALID_RESOURCE_ID,
        false
    ),
    COLORCHOOSER(
        ColorPickerR.string.color_picker_title,
        R.string.help_content_color_chooser,
        R.drawable.ic_zpaint_color_palette,
        EnumSet.of(StateChange.ALL),
        INVALID_RESOURCE_ID,
        INVALID_RESOURCE_ID,
        false
    ),
    HAND(
        R.string.button_hand,
        R.string.help_content_hand,
        R.drawable.ic_zpaint_tool_hand,
        EnumSet.of(StateChange.ALL),
        INVALID_RESOURCE_ID,
        INVALID_RESOURCE_ID,
        false
    ),
    SMUDGE(
        R.string.button_smudge,
        R.string.help_content_smudge,
        R.drawable.ic_zpaint_tool_smudge,
        EnumSet.of(StateChange.ALL),
        R.id.zpaint_tools_smudge,
        INVALID_RESOURCE_ID,
        true
    ),
    WARP(
        R.string.button_warp,
        R.string.help_content_warp,
        R.drawable.ic_zpaint_tool_warp,
        EnumSet.of(StateChange.ALL),
        R.id.zpaint_tools_warp,
        INVALID_RESOURCE_ID,
        true
    ),
    PIXEL(
        R.string.button_pixel,
        R.string.help_content_pixel,
        R.drawable.ic_zpaint_tool_pixel,
        EnumSet.of(StateChange.NEW_IMAGE_LOADED),
        INVALID_RESOURCE_ID,
        INVALID_RESOURCE_ID,
        true
    ),
    REPLACE(
        R.string.button_retouch,
        R.string.help_content_replace,
        R.drawable.ic_zpaint_tool_retouch,
        EnumSet.of(StateChange.NEW_IMAGE_LOADED),
        R.id.zpaint_tools_retouch,
        INVALID_RESOURCE_ID,
        true
    ),
    FILTER_INVERT(
        R.string.button_filter_invert,
        R.string.help_content_filter_invert,
        R.drawable.ic_zpaint_filter_invert,
        EnumSet.of(StateChange.ALL),
        R.id.zpaint_filters_invert,
        INVALID_RESOURCE_ID,
        false
    ),
    FILTER_BRIGHTNESS(
        R.string.button_filter_brightness,
        R.string.help_content_filter_brightness,
        R.drawable.ic_zpaint_filter_brightness,
        EnumSet.of(StateChange.ALL),
        R.id.zpaint_filters_brightness,
        INVALID_RESOURCE_ID,
        true
    ),
    FILTER_EXPOSURE(
        R.string.button_filter_exposure,
        R.string.help_content_filter_exposure,
        R.drawable.ic_zpaint_filter_exposure,
        EnumSet.of(StateChange.ALL),
        R.id.zpaint_filters_exposure,
        INVALID_RESOURCE_ID,
        true
    ),
    FILTER_CONTRAST(
        R.string.button_filter_contrast,
        R.string.help_content_filter_contrast,
        R.drawable.ic_zpaint_filter_contrast,
        EnumSet.of(StateChange.ALL),
        R.id.zpaint_filters_contrast,
        INVALID_RESOURCE_ID,
        true
    ),
    FILTER_BLUR(
        R.string.button_filter_blur,
        R.string.help_content_filter_blur,
        R.drawable.ic_zpaint_filter_blur,
        EnumSet.of(StateChange.ALL),
        R.id.zpaint_filters_blur,
        INVALID_RESOURCE_ID,
        true
    ),
    FILTER_BLOOM(
        R.string.button_filter_bloom,
        R.string.help_content_filter_bloom,
        R.drawable.ic_zpaint_filter_bloom,
        EnumSet.of(StateChange.ALL),
        R.id.zpaint_filters_bloom,
        INVALID_RESOURCE_ID,
        true
    ),
    FILTER_MEDIAN(
        R.string.button_filter_median,
        R.string.help_content_filter_median,
        R.drawable.ic_zpaint_filter_median,
        EnumSet.of(StateChange.ALL),
        R.id.zpaint_filters_median,
        INVALID_RESOURCE_ID,
        true
    ),
    FILTER_BILATERAL(
        R.string.button_filter_bilateral,
        R.string.help_content_filter_bilateral,
        R.drawable.ic_zpaint_filter_bilateral,
        EnumSet.of(StateChange.ALL),
        R.id.zpaint_filters_bilateral,
        INVALID_RESOURCE_ID,
        true
    ),
    FILTER_SATURATION(
        R.string.button_filter_saturation,
        R.string.help_content_filter_saturation,
        R.drawable.ic_zpaint_filter_saturation,
        EnumSet.of(StateChange.ALL),
        R.id.zpaint_filters_saturation,
        INVALID_RESOURCE_ID,
        true
    ),
    FILTER_HUE(
        R.string.button_filter_hue,
        R.string.help_content_filter_hue,
        R.drawable.ic_zpaint_filter_hue,
        EnumSet.of(StateChange.ALL),
        R.id.zpaint_filters_hue,
        INVALID_RESOURCE_ID,
        true
    ),
    FILTER_VIBRANCE(
        R.string.button_filter_vibrance,
        R.string.help_content_filter_vibrance,
        R.drawable.ic_zpaint_filter_vibrance,
        EnumSet.of(StateChange.ALL),
        R.id.zpaint_filters_vibrance,
        INVALID_RESOURCE_ID,
        true
    ),
    FILTER_TEMPERATURE(
        R.string.button_filter_temperature,
        R.string.help_content_filter_temperature,
        R.drawable.ic_zpaint_filter_temperature,
        EnumSet.of(StateChange.ALL),
        R.id.zpaint_filters_temperature,
        INVALID_RESOURCE_ID,
        true
    ),
    FILTER_HIGHLIGHTS(
        R.string.button_filter_highlights,
        R.string.help_content_filter_highlights,
        R.drawable.ic_zpaint_filter_highlights,
        EnumSet.of(StateChange.ALL),
        R.id.zpaint_filters_highlights,
        INVALID_RESOURCE_ID,
        true
    ),
    FILTER_SHADOWS(
        R.string.button_filter_shadows,
        R.string.help_content_filter_shadows,
        R.drawable.ic_zpaint_filter_shadows,
        EnumSet.of(StateChange.ALL),
        R.id.zpaint_filters_shadows,
        INVALID_RESOURCE_ID,
        true
    ),
    FILTER_SEPIA(
        R.string.button_filter_sepia,
        R.string.help_content_filter_sepia,
        R.drawable.ic_zpaint_filter_sepia,
        EnumSet.of(StateChange.ALL),
        R.id.zpaint_filters_sepia,
        INVALID_RESOURCE_ID,
        true
    ),
    FILTER_SHARPEN(
        R.string.button_filter_sharpen,
        R.string.help_content_filter_sharpen,
        R.drawable.ic_zpaint_filter_sharpen,
        EnumSet.of(StateChange.ALL),
        R.id.zpaint_filters_sharpen,
        INVALID_RESOURCE_ID,
        true
    ),
    FILTER_VIGNETTE(
        R.string.button_filter_vignette,
        R.string.help_content_filter_vignette,
        R.drawable.ic_zpaint_filter_vignette,
        EnumSet.of(StateChange.ALL),
        R.id.zpaint_filters_vignette,
        INVALID_RESOURCE_ID,
        true
    ),
    FILTER_CLARITY(
        R.string.button_filter_clarity,
        R.string.help_content_filter_clarity,
        R.drawable.ic_zpaint_filter_clarity,
        EnumSet.of(StateChange.ALL),
        R.id.zpaint_filters_clarity,
        INVALID_RESOURCE_ID,
        true
    ),
    FILTER_PIXEL(
        R.string.button_pixel,
        R.string.help_content_filter_pixel,
        R.drawable.ic_zpaint_tool_pixel,
        EnumSet.of(StateChange.ALL),
        R.id.zpaint_filters_pixel,
        INVALID_RESOURCE_ID,
        true
    ),
    FILTER_SPLASH(
        R.string.button_filter_splash,
        R.string.help_content_filter_splash,
        R.drawable.ic_zpaint_filter_splash,
        EnumSet.of(StateChange.ALL),
        R.id.zpaint_filters_splash,
        INVALID_RESOURCE_ID,
        true
    ),
    FILTER_CONTOURS(
        R.string.button_filter_contours,
        R.string.help_content_filter_contours,
        R.drawable.ic_zpaint_filter_contours,
        EnumSet.of(StateChange.ALL),
        R.id.zpaint_tools_contours,
        INVALID_RESOURCE_ID,
        true
    );

    fun shouldReactToStateChange(stateChange: StateChange): Boolean =
        stateChangeBehaviour.contains(StateChange.ALL) || stateChangeBehaviour.contains(
            stateChange
        )

    fun hasOptions(): Boolean = hasOptions
}
